#ifndef STATUS_H
#define STATUS_H

typedef enum {
  STATUS_OK,
  STATUS_CANNOT_COPY_TO_CLIPBOARD,
  STATUS_CANNOT_DETECT_DISPLAY,
  STATUS_PASSWORD_LENGTH_ERROR,
  STATUS_NOT_A_NUMBER,
  STATUS_ALLOCATION_ERROR,
  STATUS_UNKNOWN_OPTIONS,
  STATUS_USAGE_ERROR,
} StatusCode;

#endif
